// Code generated by protoc-gen-go. DO NOT EDIT.
// source: remotechg.proto

package rpccmdservice

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("remotechg.proto", fileDescriptor_36c08aa2d929cfb0) }

var fileDescriptor_36c08aa2d929cfb0 = []byte{
	// 118 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x4a, 0xcd, 0xcd,
	0x2f, 0x49, 0x4d, 0xce, 0x48, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x2d, 0x2a, 0x48,
	0x4e, 0xce, 0x4d, 0x29, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0x95, 0xe2, 0x4d, 0x49, 0x4d, 0x4b,
	0x2c, 0xcd, 0x29, 0x81, 0xc8, 0x1a, 0xc5, 0x71, 0xf1, 0xc0, 0x34, 0x24, 0xe6, 0xa5, 0xa7, 0x0a,
	0xf9, 0x71, 0xf1, 0x04, 0x81, 0xf9, 0xce, 0x10, 0xbe, 0x82, 0x1e, 0x8a, 0x76, 0x3d, 0x17, 0x88,
	0xee, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0xdf, 0xe2, 0x74, 0x29, 0x29, 0x5c, 0x2a, 0x8a,
	0x0b, 0x94, 0x18, 0x92, 0xd8, 0xc0, 0xd6, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xbb, 0x4f,
	0xdd, 0xa1, 0x97, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RemotechangeClient is the client API for Remotechange service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RemotechangeClient interface {
	RemoteChange(ctx context.Context, in *DefaultRequestMsg, opts ...grpc.CallOption) (*DefaultResp, error)
}

type remotechangeClient struct {
	cc *grpc.ClientConn
}

func NewRemotechangeClient(cc *grpc.ClientConn) RemotechangeClient {
	return &remotechangeClient{cc}
}

func (c *remotechangeClient) RemoteChange(ctx context.Context, in *DefaultRequestMsg, opts ...grpc.CallOption) (*DefaultResp, error) {
	out := new(DefaultResp)
	err := c.cc.Invoke(ctx, "/rpccmdservice.remotechange/RemoteChange", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RemotechangeServer is the server API for Remotechange service.
type RemotechangeServer interface {
	RemoteChange(context.Context, *DefaultRequestMsg) (*DefaultResp, error)
}

func RegisterRemotechangeServer(s *grpc.Server, srv RemotechangeServer) {
	s.RegisterService(&_Remotechange_serviceDesc, srv)
}

func _Remotechange_RemoteChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DefaultRequestMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemotechangeServer).RemoteChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpccmdservice.remotechange/RemoteChange",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemotechangeServer).RemoteChange(ctx, req.(*DefaultRequestMsg))
	}
	return interceptor(ctx, in, info, handler)
}

var _Remotechange_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpccmdservice.remotechange",
	HandlerType: (*RemotechangeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RemoteChange",
			Handler:    _Remotechange_RemoteChange_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "remotechg.proto",
}
