// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dhtmessage.proto

package pbdht

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Dhtmessage struct {
	Sn                   uint64   `protobuf:"varint,1,opt,name=sn,proto3" json:"sn,omitempty"`
	Msgtyp               uint32   `protobuf:"varint,2,opt,name=msgtyp,proto3" json:"msgtyp,omitempty"`
	Nbsaddr              []byte   `protobuf:"bytes,3,opt,name=nbsaddr,proto3" json:"nbsaddr,omitempty"`
	Data                 []byte   `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Dhtmessage) Reset()         { *m = Dhtmessage{} }
func (m *Dhtmessage) String() string { return proto.CompactTextString(m) }
func (*Dhtmessage) ProtoMessage()    {}
func (*Dhtmessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1ea4edd9b40c358, []int{0}
}

func (m *Dhtmessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Dhtmessage.Unmarshal(m, b)
}
func (m *Dhtmessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Dhtmessage.Marshal(b, m, deterministic)
}
func (m *Dhtmessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dhtmessage.Merge(m, src)
}
func (m *Dhtmessage) XXX_Size() int {
	return xxx_messageInfo_Dhtmessage.Size(m)
}
func (m *Dhtmessage) XXX_DiscardUnknown() {
	xxx_messageInfo_Dhtmessage.DiscardUnknown(m)
}

var xxx_messageInfo_Dhtmessage proto.InternalMessageInfo

func (m *Dhtmessage) GetSn() uint64 {
	if m != nil {
		return m.Sn
	}
	return 0
}

func (m *Dhtmessage) GetMsgtyp() uint32 {
	if m != nil {
		return m.Msgtyp
	}
	return 0
}

func (m *Dhtmessage) GetNbsaddr() []byte {
	if m != nil {
		return m.Nbsaddr
	}
	return nil
}

func (m *Dhtmessage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Dhtmessage)(nil), "pbdht.dhtmessage")
}

func init() { proto.RegisterFile("dhtmessage.proto", fileDescriptor_d1ea4edd9b40c358) }

var fileDescriptor_d1ea4edd9b40c358 = []byte{
	// 128 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x48, 0xc9, 0x28, 0xc9,
	0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2d, 0x48,
	0x4a, 0xc9, 0x28, 0x51, 0x4a, 0xe2, 0xe2, 0x42, 0x48, 0x09, 0xf1, 0x71, 0x31, 0x15, 0xe7, 0x49,
	0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x04, 0x31, 0x15, 0xe7, 0x09, 0x89, 0x71, 0xb1, 0xe5, 0x16, 0xa7,
	0x97, 0x54, 0x16, 0x48, 0x30, 0x29, 0x30, 0x6a, 0xf0, 0x06, 0x41, 0x79, 0x42, 0x12, 0x5c, 0xec,
	0x79, 0x49, 0xc5, 0x89, 0x29, 0x29, 0x45, 0x12, 0xcc, 0x0a, 0x8c, 0x1a, 0x3c, 0x41, 0x30, 0xae,
	0x90, 0x10, 0x17, 0x4b, 0x4a, 0x62, 0x49, 0xa2, 0x04, 0x0b, 0x58, 0x18, 0xcc, 0x4e, 0x62, 0x03,
	0xdb, 0x68, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x58, 0xc2, 0x95, 0xb5, 0x85, 0x00, 0x00, 0x00,
}
