// Code generated by protoc-gen-go. DO NOT EDIT.
// source: nbsnodes.proto

package pbdht

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NbsNode struct {
	Nbsaddr              []byte   `protobuf:"bytes,1,opt,name=Nbsaddr,proto3" json:"Nbsaddr,omitempty"`
	INetAddr             []byte   `protobuf:"bytes,2,opt,name=INetAddr,proto3" json:"INetAddr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NbsNode) Reset()         { *m = NbsNode{} }
func (m *NbsNode) String() string { return proto.CompactTextString(m) }
func (*NbsNode) ProtoMessage()    {}
func (*NbsNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9d585b967f51be7, []int{0}
}

func (m *NbsNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NbsNode.Unmarshal(m, b)
}
func (m *NbsNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NbsNode.Marshal(b, m, deterministic)
}
func (m *NbsNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NbsNode.Merge(m, src)
}
func (m *NbsNode) XXX_Size() int {
	return xxx_messageInfo_NbsNode.Size(m)
}
func (m *NbsNode) XXX_DiscardUnknown() {
	xxx_messageInfo_NbsNode.DiscardUnknown(m)
}

var xxx_messageInfo_NbsNode proto.InternalMessageInfo

func (m *NbsNode) GetNbsaddr() []byte {
	if m != nil {
		return m.Nbsaddr
	}
	return nil
}

func (m *NbsNode) GetINetAddr() []byte {
	if m != nil {
		return m.INetAddr
	}
	return nil
}

type NbsNodeList struct {
	Nodes                []*NbsNode `protobuf:"bytes,1,rep,name=Nodes,proto3" json:"Nodes,omitempty"`
	HaveData             bool       `protobuf:"varint,2,opt,name=HaveData,proto3" json:"HaveData,omitempty"`
	Data                 []byte     `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *NbsNodeList) Reset()         { *m = NbsNodeList{} }
func (m *NbsNodeList) String() string { return proto.CompactTextString(m) }
func (*NbsNodeList) ProtoMessage()    {}
func (*NbsNodeList) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9d585b967f51be7, []int{1}
}

func (m *NbsNodeList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NbsNodeList.Unmarshal(m, b)
}
func (m *NbsNodeList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NbsNodeList.Marshal(b, m, deterministic)
}
func (m *NbsNodeList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NbsNodeList.Merge(m, src)
}
func (m *NbsNodeList) XXX_Size() int {
	return xxx_messageInfo_NbsNodeList.Size(m)
}
func (m *NbsNodeList) XXX_DiscardUnknown() {
	xxx_messageInfo_NbsNodeList.DiscardUnknown(m)
}

var xxx_messageInfo_NbsNodeList proto.InternalMessageInfo

func (m *NbsNodeList) GetNodes() []*NbsNode {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *NbsNodeList) GetHaveData() bool {
	if m != nil {
		return m.HaveData
	}
	return false
}

func (m *NbsNodeList) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*NbsNode)(nil), "pbdht.NbsNode")
	proto.RegisterType((*NbsNodeList)(nil), "pbdht.NbsNodeList")
}

func init() { proto.RegisterFile("nbsnodes.proto", fileDescriptor_c9d585b967f51be7) }

var fileDescriptor_c9d585b967f51be7 = []byte{
	// 157 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcb, 0x4b, 0x2a, 0xce,
	0xcb, 0x4f, 0x49, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2d, 0x48, 0x4a, 0xc9,
	0x28, 0x51, 0xb2, 0xe7, 0x62, 0xf7, 0x4b, 0x2a, 0xf6, 0xcb, 0x4f, 0x49, 0x15, 0x92, 0x00, 0x33,
	0x13, 0x53, 0x52, 0x8a, 0x24, 0x18, 0x15, 0x18, 0x35, 0x78, 0x82, 0x60, 0x5c, 0x21, 0x29, 0x2e,
	0x0e, 0x4f, 0xbf, 0xd4, 0x12, 0x47, 0x90, 0x14, 0x13, 0x58, 0x0a, 0xce, 0x57, 0x4a, 0xe6, 0xe2,
	0x86, 0x1a, 0xe0, 0x93, 0x59, 0x5c, 0x22, 0xa4, 0xc2, 0xc5, 0x0a, 0x62, 0x17, 0x4b, 0x30, 0x2a,
	0x30, 0x6b, 0x70, 0x1b, 0xf1, 0xe9, 0x81, 0xad, 0xd1, 0x83, 0x2a, 0x09, 0x82, 0x48, 0x82, 0x0c,
	0xf4, 0x48, 0x2c, 0x4b, 0x75, 0x49, 0x2c, 0x49, 0x04, 0x1b, 0xc8, 0x11, 0x04, 0xe7, 0x0b, 0x09,
	0x71, 0xb1, 0xa4, 0x80, 0xc4, 0x99, 0xc1, 0x16, 0x81, 0xd9, 0x49, 0x6c, 0x60, 0x37, 0x1b, 0x03,
	0x02, 0x00, 0x00, 0xff, 0xff, 0xe8, 0xf6, 0x35, 0xcc, 0xc5, 0x00, 0x00, 0x00,
}
