package app

const (
	CMD_STOP_REQ           int32 = 1
	CMD_CONFIG_SHOW_REQ    int32 = 2
	CMD_REMOTE_SHOW_REQ    int32 = 3
	CMD_BOOTSTRAP_SHOW_REQ int32 = 4
	CMD_LICENSE_USER_SHOW_REQ int32 = 5
	CMD_HOMEIP_SAVE_REQ int32 = 6
)
