package app

const (
	CMD_STOP_REQ              int32 = 1
	CMD_CONFIG_SHOW_REQ       int32 = 2
	CMD_REMOTE_SHOW_REQ       int32 = 3
	CMD_BOOTSTRAP_SHOW_REQ    int32 = 4
	CMD_LICENSE_USER_SHOW_REQ int32 = 5
	CMD_HOMEIP_SAVE_REQ       int32 = 6
	CMD_SHADOWSOCK_SHOW       int32 = 7

	CMD_SSSERVER_SHOW   int32 = 8
	CMD_SSSERVER_UPDATE int32 = 9
	CMD_SSSERVER_REMOVE int32 = 10

	CMD_DHT_ONLINE      int32 = 11
	CMD_DHT_START       int32 = 12
	CMD_DHT_RESTART     int32 = 13
	CMD_DHT_STOP        int32 = 14

	NATIONALITY_AMERICAN       int32 = 1
	NATIONALITY_CHINA_MAINLAND int32 = 86
	NATIONALITY_JAPANESE       int32 = 81
	NATIONALITY_SINGAPORE      int32 = 65
	NATIONALITY_ENGLAND        int32 = 44

	ABROAD_AMERICAN       int = 1
	ABROAD_CHINA_MAINLAND int = 0
)
